===============================
Test cases for 7-base_geometry.py
===============================
``integer_validator(name, value)`` validates if a value is acceptable
``area()`` raises an exception

Check if the file has root permission
        >>> import os
    >>> os.access('7-base_geometry.py', os.X_OK)
    True
	>>> os.access('7-base_geometry.py', os.F_OK)
	True

Check normal cases
    >>> BaseGeometry = __import__("7-base_geometry").BaseGeometry
	>>> base_geo = BaseGeometry()
	>>> base_geo.integer_validator("square", 100)
	>>> base_geo.integer_validator("", 100)
	>>> base_geo.integer_validator("distance", 1000000000000000000000000000000000000000000000000000000000000000)
	>>> base_geo.integer_validator("", 100)

	>>> base_geo.area()
	Traceback (most recent call last):
	...
	Exception: area() is not implemented


Edge cases:
        >>> base_geo.integer_validator("square", "triangle")
	Traceback (most recent call last):
	...
	TypeError: square must be an integer
	>>> base_geo.integer_validator("distance", [4])
	Traceback (most recent call last):
	...
	TypeError: distance must be an integer
	>>> base_geo.integer_validator("check", {"value": 5})
	Traceback (most recent call last):
	...
	TypeError: check must be an integer
	>>> base_geo.integer_validator("area", 3.5)
	Traceback (most recent call last):
	...
	TypeError: area must be an integer
	>>> base_geo.integer_validator("dist", BaseGeometry)
	Traceback (most recent call last):
	...
	TypeError: dist must be an integer
	>>> base_geo.integer_validator("area", 0)
	Traceback (most recent call last):
	...
	ValueError: area must be greater than 0
	>>> base_geo.integer_validator("volume", -80)
	Traceback (most recent call last):
	...
	ValueError: volume must be greater than 0
	>>> base_geo.integer_validator("volume", -80, 40)
	Traceback (most recent call last):
	...
	TypeError: integer_validator() takes 3 positional arguments but 4 were given
	>>> base_geo.integer_validator("volume")
	Traceback (most recent call last):
	...
	TypeError: integer_validator() missing 1 required positional argument: 'value'
	>>> base_geo.integer_validator()
	Traceback (most recent call last):
	...
	TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'
	>>> base_geo.area("volume")
	Traceback (most recent call last):
	...
	TypeError: area() takes 1 positional argument but 2 were given
